// CRM Mock Data with rich interconnected records

import { Lead, Deal, Contact, Company, Activity } from '../types/crm';

export const MOCK_COMPANIES: Company[] = [
  {
    id: 'comp-1',
    name: 'Acme Corp',
    industry: 'Technology',
    employees: 250,
    revenue: '$15M',
    website: 'https://acme.example.com',
    email: 'info@acme.com',
    phone: '+91-9876543210',
    owner: 'Amit Sharma',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'comp-2',
    name: 'Globex Industries',
    industry: 'Manufacturing',
    employees: 1200,
    revenue: '$85M',
    website: 'https://globex.example.com',
    email: 'contact@globex.com',
    phone: '+91-9876543211',
    owner: 'Ravi Verma',
    createdAt: new Date('2024-02-10'),
  },
  {
    id: 'comp-3',
    name: 'TechCorp Solutions',
    industry: 'Software',
    employees: 80,
    revenue: '$5M',
    website: 'https://techcorp.example.com',
    email: 'hello@techcorp.com',
    phone: '+91-9876543212',
    owner: 'Amit Sharma',
    createdAt: new Date('2024-03-01'),
  },
  {
    id: 'comp-4',
    name: 'StartUp Innovations',
    industry: 'Fintech',
    employees: 35,
    revenue: '$2M',
    website: 'https://startup.example.com',
    email: 'team@startup.com',
    phone: '+91-9876543213',
    owner: 'Ravi Verma',
    createdAt: new Date('2024-04-12'),
  },
  {
    id: 'comp-5',
    name: 'Enterprise Logistics Ltd',
    industry: 'Logistics',
    employees: 5000,
    revenue: '$210M',
    website: 'https://enterprise.example.com',
    email: 'corporate@enterprise.com',
    phone: '+91-9876543214',
    owner: 'Amit Sharma',
    createdAt: new Date('2024-05-05'),
  },
];

export const MOCK_CONTACTS: Contact[] = [
  {
    id: 'cnt-1',
    firstName: 'Rahul',
    lastName: 'Mehta',
    email: 'rahul@acme.com',
    phone: '+91-9876543210',
    company: 'Acme Corp',
    companyId: 'comp-1',
    title: 'CTO',
    owner: 'Amit Sharma',
    createdAt: new Date('2024-01-16'),
  },
  {
    id: 'cnt-2',
    firstName: 'Priya',
    lastName: 'Nair',
    email: 'priya@globex.com',
    phone: '+91-9876543211',
    company: 'Globex Industries',
    companyId: 'comp-2',
    title: 'VP of Operations',
    owner: 'Ravi Verma',
    createdAt: new Date('2024-02-12'),
  },
  {
    id: 'cnt-3',
    firstName: 'Arjun',
    lastName: 'Kapoor',
    email: 'arjun@techcorp.com',
    phone: '+91-9876543212',
    company: 'TechCorp Solutions',
    companyId: 'comp-3',
    title: 'Product Manager',
    owner: 'Amit Sharma',
    createdAt: new Date('2024-03-05'),
  },
  {
    id: 'cnt-4',
    firstName: 'Neha',
    lastName: 'Singh',
    email: 'neha@startup.com',
    phone: '+91-9876543213',
    company: 'StartUp Innovations',
    companyId: 'comp-4',
    title: 'Founder & CEO',
    owner: 'Ravi Verma',
    createdAt: new Date('2024-04-15'),
  },
  {
    id: 'cnt-5',
    firstName: 'Vikram',
    lastName: 'Rao',
    email: 'vikram@enterprise.com',
    phone: '+91-9876543214',
    company: 'Enterprise Logistics Ltd',
    companyId: 'comp-5',
    title: 'Supply Chain Director',
    owner: 'Amit Sharma',
    createdAt: new Date('2024-05-10'),
  },
];

export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead-1',
    name: 'Siddharth Roy',
    company: 'Apex Technologies',
    email: 'siddharth@apextech.io',
    phone: '+91-9988776655',
    title: 'Head of IT',
    status: 'qualified',
    score: 87,
    source: 'website',
    owner: 'Amit Sharma',
    createdAt: new Date('2024-08-20'),
    value: 500000,
    notes: 'Interested in ERP Cloud migration.',
  },
  {
    id: 'lead-2',
    name: 'Ananya Deshmukh',
    company: 'Nexus Digital',
    email: 'ananya@nexusdigital.com',
    phone: '+91-9988776654',
    title: 'Operations Director',
    status: 'new',
    score: 72,
    source: 'referral',
    owner: 'Ravi Verma',
    createdAt: new Date('2024-08-25'),
    value: 350000,
    notes: 'Referred by Globex team.',
  },
  {
    id: 'lead-3',
    name: 'Karan Patel',
    company: 'Vanguard Systems',
    email: 'karan@vanguard.org',
    phone: '+91-9988776653',
    title: 'Procurement Lead',
    status: 'contacted',
    score: 65,
    source: 'cold-call',
    owner: 'Amit Sharma',
    createdAt: new Date('2024-08-18'),
    value: 250000,
  },
  {
    id: 'lead-4',
    name: 'Sneha Kulkarni',
    company: 'Zenith Labs',
    email: 'sneha@zenithlabs.com',
    phone: '+91-9988776652',
    title: 'Chief Strategy Officer',
    status: 'qualified',
    score: 92,
    source: 'email',
    owner: 'Ravi Verma',
    createdAt: new Date('2024-08-15'),
    value: 750000,
  },
  {
    id: 'lead-5',
    name: 'Deepak Joshi',
    company: 'Starlight Retail',
    email: 'deepak@starlight.in',
    phone: '+91-9988776651',
    title: 'VP Operations',
    status: 'converted',
    score: 95,
    source: 'event',
    owner: 'Amit Sharma',
    createdAt: new Date('2024-08-10'),
    value: 1200000,
    convertedCompanyId: 'comp-1',
    convertedContactId: 'cnt-1',
    convertedDealId: 'deal-1',
  },
];

export const MOCK_DEALS: Deal[] = [
  {
    id: 'deal-1',
    name: 'Acme - ERP Cloud Contract',
    company: 'Acme Corp',
    companyId: 'comp-1',
    contactId: 'cnt-1',
    value: 500000,
    currency: '₹',
    stage: 'qualification',
    probability: 80,
    owner: 'Amit Sharma',
    closingDate: new Date('2024-09-30'),
    description: 'Enterprise ERP core modules setup',
    createdAt: new Date('2024-08-01'),
  },
  {
    id: 'deal-2',
    name: 'Globex - Factory Automation',
    company: 'Globex Industries',
    companyId: 'comp-2',
    contactId: 'cnt-2',
    value: 750000,
    currency: '₹',
    stage: 'proposal',
    probability: 60,
    owner: 'Ravi Verma',
    closingDate: new Date('2024-10-15'),
    description: 'Supply chain & inventory sync module',
    createdAt: new Date('2024-08-05'),
  },
  {
    id: 'deal-3',
    name: 'TechCorp - SaaS Licenses',
    company: 'TechCorp Solutions',
    companyId: 'comp-3',
    contactId: 'cnt-3',
    value: 350000,
    currency: '₹',
    stage: 'negotiation',
    probability: 50,
    owner: 'Amit Sharma',
    closingDate: new Date('2024-09-20'),
    description: '50 seat annual plan',
    createdAt: new Date('2024-08-10'),
  },
  {
    id: 'deal-4',
    name: 'StartUp - Seed ERP Deployment',
    company: 'StartUp Innovations',
    companyId: 'comp-4',
    contactId: 'cnt-4',
    value: 1200000,
    currency: '₹',
    stage: 'won',
    probability: 100,
    owner: 'Ravi Verma',
    closingDate: new Date('2024-08-30'),
    description: 'Full ERP stack onboarding',
    createdAt: new Date('2024-07-20'),
  },
  {
    id: 'deal-5',
    name: 'Enterprise - Fleet Tracker integration',
    company: 'Enterprise Logistics Ltd',
    companyId: 'comp-5',
    contactId: 'cnt-5',
    value: 900000,
    currency: '₹',
    stage: 'new',
    probability: 30,
    owner: 'Amit Sharma',
    closingDate: new Date('2024-11-30'),
    description: 'Custom API integration for fleet tracking',
    createdAt: new Date('2024-08-28'),
  },
];

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    type: 'meeting',
    subject: 'ERP Requirement Discovery Call',
    description: 'Discussed cloud migration timelines with Rahul Mehta.',
    relatedTo: 'comp-1',
    relatedType: 'company',
    owner: 'Amit Sharma',
    date: new Date('2024-08-28T10:30:00'),
    completed: true,
  },
  {
    id: 'act-2',
    type: 'task',
    subject: 'Send Factory Automation Proposal',
    description: 'Drafted custom quote for Globex Industries.',
    relatedTo: 'deal-2',
    relatedType: 'deal',
    owner: 'Ravi Verma',
    date: new Date('2024-08-29T14:00:00'),
    completed: false,
  },
  {
    id: 'act-3',
    type: 'call',
    subject: 'Follow up on License Pricing',
    description: 'Check in with Arjun Kapoor regarding pricing discounts.',
    relatedTo: 'cnt-3',
    relatedType: 'contact',
    owner: 'Amit Sharma',
    date: new Date('2024-08-30T11:00:00'),
    completed: false,
  },
];
