// Inventory V1 Mock Data with Indian Warehouse Locations & ₹ Currency

import { Product, Warehouse, WarehouseStock, StockMovement } from '../types/inventory';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    sku: 'PRD-LTP-01',
    name: 'Laptop Pro 15"',
    category: 'Hardware',
    unit: 'Units',
    sellingPrice: 70000,
    costPrice: 52000,
    stock: 130,
    reorderLevel: 25,
    status: 'active',
    createdAt: new Date('2024-01-10'),
  },
  {
    id: 'prod-2',
    sku: 'PRD-MNT-02',
    name: '4K Monitor 27"',
    category: 'Peripherals',
    unit: 'Units',
    sellingPrice: 15000,
    costPrice: 10500,
    stock: 18, // Low Stock!
    reorderLevel: 20,
    status: 'active',
    createdAt: new Date('2024-02-05'),
  },
  {
    id: 'prod-3',
    sku: 'PRD-KBD-03',
    name: 'Mechanical Keyboard RGB',
    category: 'Peripherals',
    unit: 'Units',
    sellingPrice: 4500,
    costPrice: 2800,
    stock: 260,
    reorderLevel: 30,
    status: 'active',
    createdAt: new Date('2024-03-12'),
  },
  {
    id: 'prod-4',
    sku: 'PRD-IOT-04',
    name: 'IoT Gateway Hub',
    category: 'Networking',
    unit: 'Sets',
    sellingPrice: 180000,
    costPrice: 135000,
    stock: 12,
    reorderLevel: 5,
    status: 'active',
    createdAt: new Date('2024-04-18'),
  },
  {
    id: 'prod-5',
    sku: 'PRD-SNS-05',
    name: 'Industrial Sensors Kit',
    category: 'Electronics',
    unit: 'Kits',
    sellingPrice: 6000,
    costPrice: 3800,
    stock: 45,
    reorderLevel: 15,
    status: 'active',
    createdAt: new Date('2024-05-20'),
  },
];

export const MOCK_WAREHOUSES: Warehouse[] = [
  {
    id: 'wh-1',
    code: 'WH-MUM',
    name: 'Mumbai Central Logistics Hub',
    location: 'Bhiwandi, Mumbai, Maharashtra',
    manager: 'Rajesh Kumar',
    phone: '+91-9876500001',
    email: 'mumbai.wh@erp.example.com',
  },
  {
    id: 'wh-2',
    code: 'WH-DEL',
    name: 'Delhi NCR Fulfillment Depot',
    location: 'Gurugram, Haryana',
    manager: 'Sunil Sharma',
    phone: '+91-9876500002',
    email: 'delhi.wh@erp.example.com',
  },
  {
    id: 'wh-3',
    code: 'WH-BLR',
    name: 'Bangalore Tech Depot',
    location: 'Whitefield, Bangalore, Karnataka',
    manager: 'Karthik Rao',
    phone: '+91-9876500003',
    email: 'blr.wh@erp.example.com',
  },
];

export const MOCK_WAREHOUSE_STOCKS: WarehouseStock[] = [
  {
    id: 'ws-1',
    productId: 'prod-1',
    productName: 'Laptop Pro 15"',
    sku: 'PRD-LTP-01',
    warehouseId: 'wh-1',
    warehouseName: 'Mumbai Central Logistics Hub',
    available: 70,
    reserved: 10,
    total: 80,
  },
  {
    id: 'ws-2',
    productId: 'prod-1',
    productName: 'Laptop Pro 15"',
    sku: 'PRD-LTP-01',
    warehouseId: 'wh-2',
    warehouseName: 'Delhi NCR Fulfillment Depot',
    available: 45,
    reserved: 5,
    total: 50,
  },
  {
    id: 'ws-3',
    productId: 'prod-2',
    productName: '4K Monitor 27"',
    sku: 'PRD-MNT-02',
    warehouseId: 'wh-1',
    warehouseName: 'Mumbai Central Logistics Hub',
    available: 8,
    reserved: 2,
    total: 10,
  },
  {
    id: 'ws-4',
    productId: 'prod-2',
    productName: '4K Monitor 27"',
    sku: 'PRD-MNT-02',
    warehouseId: 'wh-2',
    warehouseName: 'Delhi NCR Fulfillment Depot',
    available: 5,
    reserved: 3,
    total: 8,
  },
  {
    id: 'ws-5',
    productId: 'prod-3',
    productName: 'Mechanical Keyboard RGB',
    sku: 'PRD-KBD-03',
    warehouseId: 'wh-1',
    warehouseName: 'Mumbai Central Logistics Hub',
    available: 150,
    reserved: 20,
    total: 170,
  },
  {
    id: 'ws-6',
    productId: 'prod-3',
    productName: 'Mechanical Keyboard RGB',
    sku: 'PRD-KBD-03',
    warehouseId: 'wh-3',
    warehouseName: 'Bangalore Tech Depot',
    available: 80,
    reserved: 10,
    total: 90,
  },
];

export const MOCK_MOVEMENTS: StockMovement[] = [
  {
    id: 'sm-1',
    date: new Date('2024-09-01T10:30:00'),
    productId: 'prod-1',
    productName: 'Laptop Pro 15"',
    sku: 'PRD-LTP-01',
    warehouseId: 'wh-1',
    warehouseName: 'Mumbai Central Logistics Hub',
    type: 'Purchase',
    quantity: 50,
    referenceCode: 'PO-9912',
    notes: 'Received bulk order from manufacturer.',
  },
  {
    id: 'sm-2',
    date: new Date('2024-09-01T14:15:00'),
    productId: 'prod-2',
    productName: '4K Monitor 27"',
    sku: 'PRD-MNT-02',
    warehouseId: 'wh-1',
    warehouseName: 'Mumbai Central Logistics Hub',
    type: 'Sale',
    quantity: -10,
    referenceCode: 'SO-00124',
    notes: 'Dispatched for Acme Corp Sales Order.',
  },
  {
    id: 'sm-3',
    date: new Date('2024-08-31T11:00:00'),
    productId: 'prod-3',
    productName: 'Mechanical Keyboard RGB',
    sku: 'PRD-KBD-03',
    warehouseId: 'wh-2',
    warehouseName: 'Delhi NCR Fulfillment Depot',
    type: 'Transfer',
    quantity: -20,
    referenceCode: 'TRF-0044',
    notes: 'Inter-warehouse stock rebalancing.',
  },
  {
    id: 'sm-4',
    date: new Date('2024-08-28T09:45:00'),
    productId: 'prod-4',
    productName: 'IoT Gateway Hub',
    sku: 'PRD-IOT-04',
    warehouseId: 'wh-1',
    warehouseName: 'Mumbai Central Logistics Hub',
    type: 'Sale',
    quantity: -2,
    referenceCode: 'SO-00123',
    notes: 'Dispatched for Globex Industries.',
  },
];
