import React, { createContext, useContext, useEffect, useState } from 'react';
import { api } from '../../lib/api';
import { Account, AccountType, Expense, ExpenseCategory, Invoice, InvoiceItem, InvoiceStatus, PaymentMethod, PaymentRecord } from '../../types/finance';
import { SalesOrder } from '../../types/sales';

interface FinanceContextType {
  invoices: Invoice[]; payments: PaymentRecord[]; expenses: Expense[]; accounts: Account[]; loading: boolean; error: string | null; reload: () => Promise<void>;
  addInvoice: (invoice: Omit<Invoice, 'id' | 'code' | 'issueDate' | 'paidAmount' | 'outstandingAmount'>) => Promise<Invoice | undefined>; updateInvoice: (id: string, fields: Partial<Invoice>) => Promise<void>; updateInvoiceStatus: (id: string, status: InvoiceStatus) => Promise<void>; deleteInvoice: (id: string) => Promise<void>; convertOrderToInvoice: (order: SalesOrder) => Promise<Invoice | undefined>;
  recordPayment: (invoiceCode: string, amount: number, method: PaymentMethod, referenceNumber?: string) => Promise<PaymentRecord | null>; addExpense: (expense: Omit<Expense, 'id' | 'code' | 'date'>) => Promise<Expense | undefined>; updateExpense: (id: string, fields: Partial<Expense>) => Promise<void>; deleteExpense: (id: string) => Promise<void>;
}
const FinanceContext = createContext<FinanceContextType | undefined>(undefined);
const invoiceStatus: Record<string, string> = { draft: 'DRAFT', sent: 'SENT', paid: 'PAID', overdue: 'OVERDUE' };
const fromInvoiceStatus: Record<string, InvoiceStatus> = { DRAFT: 'draft', ISSUED: 'sent', SENT: 'sent', PARTIAL_PAID: 'sent', PAID: 'paid', OVERDUE: 'overdue', CANCELLED: 'draft' };
const methods: Record<string, string> = { 'Bank Transfer': 'BANK_TRANSFER', UPI: 'UPI', Card: 'CREDIT_CARD', Cash: 'CASH' };
const fromMethod: Record<string, PaymentMethod> = { BANK_TRANSFER: 'Bank Transfer', UPI: 'UPI', CREDIT_CARD: 'Card', CASH: 'Cash' };
const categories: Record<string, string> = { Office: 'SUPPLIES', Travel: 'TRAVEL', Software: 'OTHER', Equipment: 'OTHER', Utilities: 'UTILITIES', Other: 'OTHER' };
const fromCategory: Record<string, ExpenseCategory> = { TRAVEL: 'Travel', MEALS: 'Other', SUPPLIES: 'Office', UTILITIES: 'Utilities', RENT: 'Other', SALARIES: 'Other', MAINTENANCE: 'Other', ADVERTISING: 'Other', OTHER: 'Other' };
const accountTypes: Record<string, string> = { Asset: 'ASSET', Liability: 'LIABILITY', Revenue: 'REVENUE', Expense: 'EXPENSE' };
const fromAccountType: Record<string, AccountType> = { ASSET: 'Asset', LIABILITY: 'Liability', REVENUE: 'Revenue', EXPENSE: 'Expense', EQUITY: 'Asset', ACCOUNTS_RECEIVABLE: 'Asset', ACCOUNTS_PAYABLE: 'Liability' };
const mapInvoiceItem = (item: any): InvoiceItem => ({ id: item.id, description: item.product?.name || item.productId, quantity: Number(item.quantity), unitPrice: Number(item.unitPrice), total: Number(item.lineTotal) });
const mapInvoice = (item: any): Invoice => ({ id: item.id, code: item.code, customerName: item.company?.name || item.companyId, companyId: item.companyId, salesOrderId: item.salesOrderId, salesOrderCode: item.salesOrder?.code, items: (item.items || []).map(mapInvoiceItem), subtotal: Number(item.subtotal), tax: Number(item.tax), total: Number(item.total), paidAmount: Number(item.paidAmount), outstandingAmount: Number(item.outstandingAmount), currency: '₹', status: fromInvoiceStatus[item.status] || 'draft', issueDate: new Date(item.issueDate), dueDate: new Date(item.dueDate || item.issueDate), notes: '' });
const mapPayment = (item: any): PaymentRecord => ({ id: item.id, code: item.id, invoiceCode: item.invoice?.code || item.invoiceId, invoiceId: item.invoiceId, customerName: item.invoice?.company?.name || '', amount: Number(item.amount), method: fromMethod[item.method] || 'Bank Transfer', paymentDate: new Date(item.paymentDate), status: 'Success', referenceNumber: item.transactionRef });
const mapExpense = (item: any): Expense => ({ id: item.id, code: item.id, title: item.description || 'Expense', category: fromCategory[item.category] || 'Other', amount: Number(item.amount), date: new Date(item.expenseDate), vendor: item.supplier?.name || '', description: item.description, status: 'Approved' });
const mapAccount = (item: any): Account => ({ id: item.id, name: item.name, type: fromAccountType[item.accountType] || 'Asset', balance: Number(item.balance), code: item.id });

export const FinanceProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [invoices, setInvoices] = useState<Invoice[]>([]); const [payments, setPayments] = useState<PaymentRecord[]>([]); const [expenses, setExpenses] = useState<Expense[]>([]); const [accounts, setAccounts] = useState<Account[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const run = async <T,>(operation: () => Promise<T>) => { try { setError(null); return await operation(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Finance request failed'); return undefined; } };
  const reload = async () => { setLoading(true); try { const [i, p, e, a] = await Promise.all([api.get<any[]>('/invoices'), api.get<any[]>('/payments'), api.get<any[]>('/expenses'), api.get<any[]>('/accounts')]); setInvoices(i.map(mapInvoice)); setPayments(p.map(mapPayment)); setExpenses(e.map(mapExpense)); setAccounts(a.map(mapAccount)); setError(null); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load finance data'); } finally { setLoading(false); } };
  useEffect(() => { void reload(); }, []);
  const addInvoice = async (data: Omit<Invoice, 'id' | 'code' | 'issueDate' | 'paidAmount' | 'outstandingAmount'>) => { const item = await run(() => api.post<any>('/invoices', { companyId: data.companyId || '', salesOrderId: data.salesOrderId, status: invoiceStatus[data.status], subtotal: data.subtotal, tax: data.tax, total: data.total, outstandingAmount: data.total, dueDate: data.dueDate })); if (!item) return; for (const line of data.items.filter((candidate) => (candidate as InvoiceItem & { productId?: string }).productId)) { const invoiceLine = line as InvoiceItem & { productId: string }; await run(() => api.post(`/invoices/${item.id}/items`, { productId: invoiceLine.productId, quantity: line.quantity, unitPrice: line.unitPrice, lineTotal: line.total })); } const result = mapInvoice({ ...item, items: data.items }); setInvoices((current) => [result, ...current]); return result; };
  const updateInvoice = async (id: string, data: Partial<Invoice>) => { await run(() => api.patch(`/invoices/${id}`, { companyId: data.companyId, status: data.status && invoiceStatus[data.status], subtotal: data.subtotal, tax: data.tax, total: data.total, dueDate: data.dueDate })); await reload(); };
  const updateInvoiceStatus = async (id: string, status: InvoiceStatus) => updateInvoice(id, { status });
  const deleteInvoice = async (id: string) => { await run(() => api.delete(`/invoices/${id}`)); setInvoices((current) => current.filter((item) => item.id !== id)); };
  const convertOrderToInvoice = async (order: SalesOrder) => { const item = await run(() => api.post<any>(`/orders/${order.id}/convert-to-invoice`, {})); await reload(); return item ? mapInvoice(item) : undefined; };
  const recordPayment = async (invoiceCode: string, amount: number, method: PaymentMethod, referenceNumber?: string) => { const invoice = invoices.find((item) => item.code === invoiceCode || item.id === invoiceCode); if (!invoice) return null; const item = await run(() => api.post<any>('/payments/record', { invoiceId: invoice.id, amount, method: methods[method], transactionRef: referenceNumber })); await reload(); return item ? mapPayment(item) : null; };
  const addExpense = async (data: Omit<Expense, 'id' | 'code' | 'date'>) => { const item = await run(() => api.post<any>('/expenses', { category: categories[data.category], amount: data.amount, description: data.description || data.title, expenseDate: new Date() })); if (!item) return; const result = mapExpense(item); setExpenses((current) => [result, ...current]); return result; };
  const updateExpense = async (id: string, data: Partial<Expense>) => { await run(() => api.patch(`/expenses/${id}`, { category: data.category && categories[data.category], amount: data.amount, description: data.description || data.title, expenseDate: data.date })); await reload(); };
  const deleteExpense = async (id: string) => { await run(() => api.delete(`/expenses/${id}`)); setExpenses((current) => current.filter((item) => item.id !== id)); };
  return <FinanceContext.Provider value={{ invoices, payments, expenses, accounts, loading, error, reload, addInvoice, updateInvoice, updateInvoiceStatus, deleteInvoice, convertOrderToInvoice, recordPayment, addExpense, updateExpense, deleteExpense }}>{children}</FinanceContext.Provider>;
};

export const useFinance = () => { const context = useContext(FinanceContext); if (!context) throw new Error('useFinance must be used within a FinanceProvider'); return context; };
